var clusterTemplate = {};

clusterTemplate.Health = [
    '<a id="clusterHealthButton" class="btn btn-<%- statusClass %> " rel="popRight" data-trigger="hover"',
    'data-content="Status: <span class=\'label label-<%- statusClassLabel %>\'><%- statusText %></span>" data-html="true"',
    'href="#cluster" role="button">',
    '<i class="icon-info-sign"></i> <%- cluster_name %></a>'
].join("\n");

clusterTemplate.HealthDescribe = [
    '<div class="row-fluid" style="padding: 15px;">',
    '<div class="span2 pull-left"><a href="#refreshCluster" class="btn btn-mini"  rel="tipRight" data-placement="bottom" data-html="true" data-title="Refreshing every <%- polling/1000 %> seconds.<br/>Click to Force Refresh."><i class="icon-refresh"></i> <%- lastUpdateTime %></a></div>',
    '<div class="text-center span8"><span style="font-size: 28px;">Cluster Overview</span></div>',
    '<div class="span2"></div>',
    '</div>',

    '<div class="row-fluid">',

    '<div class="grid" style="margin-top: 10px;">',
    '<div class="grid-title">',
    '<div class="pull-left">',
    '<div class="icon-title"><i class="icon-bar-chart"></i></div>',
    '<span>Cluster Statistics</span>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="grid-content overflow">',

    '<div class="row-fluid center-table">',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- health.number_of_nodes %></span><span>Nodes</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- indices.shards.total %></span><span>Total Shards</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- indices.shards.successful %></span><span>Successful Shards</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- indices.count %></span><span>Indices</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- indices.docs.count %></span><span>Total Documents</span>',
    '</div></div>',
    '<div class="span2">',
    '<div class="well stat-box"><span class="stat-detail"><%- indices.store.size %></span><span>Total Size</span>',
    '</div></div>',
    '</div>',
    '<div class="clear"></div>',
    '</div>',
    /*    '<div class="grid-content">',
     '<div class="clear"></div>',
     '<div class="clearfix"></div>',
     '</div>',*/
    '</div>', // grid

    '</div>', // row
    '<div class="row-fluid">',
    '<div class="span6">',
    '<div class="grid">',
    '<div class="grid-title">',
    '<div class="pull-left">',
    '<div class="icon-title"><i class="icon-ambulance"></i></div>',
    '<span>Cluster Health</span>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="grid-content overflow">',

    '<table class="table table-striped table-hover table-bordered  center-table">',
    '<tr>',
    '<td>Status</td>',
    '<td><span class="label label-<%- health.statusClassLabel %>"><%- health.statusText %></span></td>',
    '</tr>',
    '<tr>',
    '<td>Timed Out?</td>',
    '<td><%- health.timed_out %></td>',
    '</tr>',
    '<tr>',
    '<td># Nodes</td>',
    '<td><%- health.number_of_nodes %></td>',
    '</tr>',
    '<tr>',
    '<td># Data Nodes</td>',
    '<td><%- health.number_of_data_nodes %></td>',
    '</tr>',
    '<tr>',
    '<td>Active Primary Shards</td>',
    '<td><%- health.active_primary_shards %></td>',
    '</tr>',
    '<tr>',
    '<td>Active Shards</td>',
    '<td><%- health.active_shards%></td>',
    '</tr>',
    '<tr>',
    '<td>Relocating Shards</td>',
    '<td><%- health.relocating_shards%></td>',
    '</tr>',
    '<tr>',
    '<td>Initializing Shards</td>',
    '<td><%- health.initializing_shards%></td>',
    '</tr>',
    '<tr>',
    '<td>Unassigned Shards</td>',
    '<td><%- health.unassigned_shards%></td>',
    '</tr>',
    '</table>',

    '<div class="clear"></div>',
    '</div>',
    '<div class="grid-content">',
    '<div class="clear"></div>',
    '<div class="clearfix"></div>',
    '</div>',
    '</div>',

    '</div>', // span

    '<div class="span6">',
    '<div class="grid">',
    '<div class="grid-title">',
    '<div class="pull-left">',
    '<div class="icon-title"><i class="icon-list"></i></div>',
    '<span>Indices</span>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="clearfix"></div>',
    '</div>',
    '<div class="grid-content overflow">',
    '<% if (!jQuery.isEmptyObject(indices.indices)) { %>',
    '<table class="table table-bordered table-striped table-hover" id="indicesTable">',
    '<thead>',
    '<tr><th>Index</th><th># Docs</th><th>Primary Size</th><th># Shards</th><th># Replicas</th><th>Status</th></tr>',
    '</thead>',
    '<tbody>',
    '<% _.each(indices.indices, function(index) { %>',
    '<tr><td>',
    '<a href="#index/<%- index.id %>"  rel="tipRight" data-placement="bottom" data-title="Index Information"><%- index.name %></a>',
    '</td><td><%- index.total.docs.count %></td><td><%- index.total.store.size %></td><td><%- index.numshards %></td><td><%- index.numreplicas %></td><td><%- index.status %></td></tr>',
    '<% }); %>',
    '</tbody>',
    '</table>',
    '<% } %>',

    '<div class="clear"></div>',
    '</div>',
    '<div class="grid-content">',
    '<div class="clear"></div>',
    '<div class="clearfix"></div>',
    '</div>',
    '</div>',
    '</div>'
].join("\n");
